spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username: marcella
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

