spring:
  datasource:
    url: jdbc:postgresql://db.zuroxkolzxlgzjszxsoa.supabase.co:5432/postgres
    username: postgres
    password: Marcella@27

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: pearlautherizer@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
